"""The Store interface. See SCHEMA.md §0 for the layout it addresses."""

from __future__ import annotations

from typing import Protocol

from core.models import Page, SourcePage


class Store(Protocol):
    def read_page(self, slug: str) -> Page | None: ...

    def write_page(self, page: Page) -> bool: ...

    def list_pages(self) -> list[str]: ...

    def read_index(self) -> str: ...

    def write_index(self, content: str) -> None: ...

    def append_log(self, entry: str) -> None: ...

    def read_raw(self, doc_id: str) -> str: ...

    def read_source_page(self, doc_id: str) -> SourcePage | None: ...

    def write_source_page(self, page: SourcePage) -> bool: ...
